package constants

const ENV_APP_CONFIG_GROUPS = "APP_CONFIG_GROUPS"

const ENV_MAIL_HOST = "MAIL_HOST"
const ENV_MAIL_PORT = "MAIL_PORT"
const ENV_MAIL_USER = "MAIL_USER"
const ENV_MAIL_PASSWORD = "MAIL_PASSWORD"
const ENV_MAIL_FROM = "MAIL_FROM"

const ENV_RECAPTCHA_SECRET_KEY = "RECAPTCHA_SECRET_KEY"
const ENV_ENABLE_USER_SCHEMA_MAPPING = "ENABLE_USER_SCHEMA_MAPPING"
const ENV_ENABLE_FLUENTD = "ENABLE_FLUENTD"
const ENV_MAX_USER_SESSION_LIMIT = "MAX_USER_SESSION_LIMIT"
const ENV_AUTO_LOGOUT_DURATION = "AUTO_LOGOUT_DURATION"
