package constants

const ENV_APP_CONFIG_GROUPS = "APP_CONFIG_GROUPS"

const ENV_MAIL_HOST = "MAIL_HOST"
const ENV_MAIL_PORT = "MAIL_PORT"
const ENV_MAIL_USER = "MAIL_USER"
const ENV_MAIL_PASSWORD = "MAIL_PASSWORD"
const ENV_MAIL_FROM = "MAIL_FROM"

const ENV_RECAPTCHA_SECRET_KEY = "RECAPTCHA_SECRET_KEY"
const ENV_ENABLE_USER_SCHEMA_MAPPING = "ENABLE_USER_SCHEMA_MAPPING"
const ENV_ENABLE_FLUENTD = "ENABLE_FLUENTD"
const ENV_MAX_USER_SESSION_LIMIT = "MAX_USER_SESSION_LIMIT"
const ENV_AUTO_LOGOUT_DURATION = "AUTO_LOGOUT_DURATION"

const (
	ENV_FILTER_SCHEMA_NAMES  = "FILTER_SCHEMA_NAMES"
	ENV_FILTER_PROCESS_NAMES = "FILTER_PROCESS_NAMES"
	// Parameter untuk mode sandbox
	PARAM_CODE_SS_AUTH_URL_SANDBOX    = "SS_AUTH_URL_SANDBOX"    // URL authentication satusehat sandbox
	PARAM_CODE_SS_BASE_URL_SANDBOX    = "SS_BASE_URL_SANDBOX"    // Base URL satusehat sandbox
	PARAM_CODE_SS_CONSENT_URL_SANDBOX = "SS_CONSENT_URL_SANDBOX" // URL Consent satusehat sandbox

	// Parameter untuk mode production
	PARAM_CODE_SS_AUTH_URL_PRODUCTION    = "SS_AUTH_URL_PRODUCTION"    // URL authentication satusehat production
	PARAM_CODE_SS_BASE_URL_PRODUCTION    = "SS_BASE_URL_PRODUCTION"    // Base URL satusehat production
	PARAM_CODE_SS_CONSENT_URL_PRODUCTION = "SS_CONSENT_URL_PRODUCTION" // URL Consent satusehat production

	// Parameter untuk API access code
	PARAM_CODE_SS_CLIENT_ID       = "SS_CLIENT_ID"       // Client ID from API code access satusehat
	PARAM_CODE_SS_CLIENT_SECRET   = "SS_CLIENT_SECRET"   // Client Secret from API code access satusehat
	PARAM_CODE_SS_ORGANIZATION_ID = "SS_ORGANIZATION_ID" // Organization ID from API code access satusehat
	PARAM_CODE_SS_MODE_ACCESS     = "SS_MODE_ACCESS"     // Mode access API satusehat (contoh: SANDBOX atau PRODUCTION)
	PARAM_GROUP_SATUSEHAT         = "SATUSEHAT"          // Group parameter satusehat

	MODE_PRODUCTION = "PRODUCTION"

	QUEUE_NAME_WEBHOOK_UPDATE_STATUS = "WEBHOOK_UPDATE_STATUS"
	ENV_CHECK_QUEUE_INTERVAL         = "CHECK_QUEUE_INTERVAL"

	QUEUE_NAME_CREATE_ENCOUNTER = "CREATE_ENCOUNTER"
	QUEUE_NAME_FINISH_ENCOUNTER = "FINISH_ENCOUNTER"

	QUEUE_NAME_CREATE_CONDITION = "CREATE_CONDITION"

	STATUS_DOC_IN_PROGRESS = "I"

	STATUS_SUCCESS = "S"
	STATUS_FAIL    = "E"

	EVENT_UPDATE_STATUS = "UPDATE_STATUS"

	// Status Send SS Constants
	COMBO_VALUE_ENCOUNTER             = "ENCOUNTER"
	COMBO_VALUE_CONDITION             = "CONDITION"
	COMBO_VALUE_OBSERVATION           = "OBSERVATION"
	COMBO_VALUE_PROCEDURE             = "PROCEDURE"
	COMBO_VALUE_COMPOSITION           = "COMPOSITION"
	COMBO_VALUE_MEDICATION            = "MEDICATION"
	COMBO_VALUE_MEDICATIONREQUEST     = "MEDICATIONREQUEST"
	COMBO_VALUE_MEDICATIONDISPENSE    = "MEDICATIONDISPENSE"
	COMBO_VALUE_ALLERGYINTOLERANCE    = "ALLERGYINTOLERANCE"
	COMBO_VALUE_IMAGINGSTUDY          = "IMAGINGSTUDY"
	COMBO_VALUE_SERVICEREQUEST        = "SERVICEREQUEST"
	COMBO_VALUE_CLINICALIMPRESSION    = "CLINICALIMPRESSION"
	COMBO_VALUE_IMMUNIZATION          = "IMMUNIZATION"
	COMBO_VALUE_QUESTIONNAIRERESPONSE = "QUESTIONNAIRERESPONSE"
	COMBO_VALUE_MEDICATIONSTATEMENT   = "MEDICATIONSTATEMENT"
	COMBO_VALUE_CAREPLAN              = "CAREPLAN"
	COMBO_VALUE_SPECIMEN              = "SPECIMEN"
	COMBO_VALUE_DIAGNOSTICREPORT      = "DIAGNOSTICREPORT"
	COMBO_VALUE_EPISODEOFCARE         = "EPISODEOFCARE"
)
