version: "3.0"
services:
  app:
    image: ${REGISTRY_URL:-jleaf.org:5011}/ssbackend:${APP_VERSION:-1.0.0}${MODE}
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    tty: true
    ports: 
      - "${SERVER_PORT:-5005}:5005"
    volumes:
      - "./log:/app/logs"
    environment: 
      DB_HOST: ${DB_HOST:-172.17.0.1}
      DB_PORT: ${DB_PORT:-5433}
      DB_NAME: ${DB_NAME:-satusehat_dev}
      DB_USER: ${DB_USER:-sts}
      DB_PASSWORD: ${DB_PASSWORD:-Awesome123!}
      LOG_FILE: ${LOG_FILE:-/app/logs/ssbackend.log}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      TZ: ${TIMEZONE:-Asia/Jakarta}
      DB_POOL_MAX_CONNS: ${DB_POOL_MAX_CONNS:-5}
      DB_APP_NAME: ${DB_APP_NAME:-ssbackend}
      TEMPLATE_DB_FILE: ${TEMPLATE_DB_FILE:-/asset/ssdbtemplate.custom}
      ENABLE_USER_SCHEMA_MAPPING: ${ENABLE_USER_SCHEMA_MAPPING:-false}
      