go get -d git.solusiteknologi.co.id/goleaf/goleafcore@main
go get -d git.solusiteknologi.co.id/goleaf/glauth
go get -d git.solusiteknologi.co.id/goleaf/glwebhook
go get -d git.solusiteknologi.co.id/goleaf/glqueue
go get -d git.solusiteknologi.co.id/goleaf/glautonumber 
go get -d git.solusiteknologi.co.id/goleaf/glcommon 
go get -d git.solusiteknologi.co.id/goleaf/glrecaptcha
go get -d git.solusiteknologi.co.id/goleaf/glregistration
go get -d git.solusiteknologi.co.id/goleaf/glhttp
